Repository Christian-Petter-Remman/idatt2003-group44-r-h-boardgame-app, pull requests merged in 2025-05, with the labels that each got.

#91 feat: Dialogs
  src/main/java/edu/ntnu/idi/idatt/view/common/intro/StartScreenView.java
  src/main/resources/home_screen/farmerfredrik.png
Labels: documentation, enhancement

#93 feat: Start Screen - Split logic into Model, View and Controller
  src/main/java/edu/ntnu/idi/idatt/controller/common/StartScreenController.java
  src/main/java/edu/ntnu/idi/idatt/model/common/intro/StartScreenModel.java
  src/main/java/edu/ntnu/idi/idatt/view/common/intro/StartScreenView.java
Labels: bug

#102 Fix/json/remove json from gitignore
  .gitignore
  data/custom_boards/snakes_and_ladders/default.json
  data/custom_boards/snakes_and_ladders/easy.json
  data/custom_boards/snakes_and_ladders/hard.json
  data/custom_boards/snakes_and_ladders/random1.json
  data/custom_boards/snakes_and_ladders/random2.json
  data/custom_boards/snakes_and_ladders/random3.json
  data/custom_boards/snakes_and_ladders/random4.json
  data/custom_boards/snakes_and_ladders/random5.json
  data/custom_boards/snakes_and_ladders/random6.json
  data/custom_boards/snakes_and_ladders/random7.json
  data/custom_boards/snakes_and_ladders/random8.json
  data/dialogs/dialogs.json
  data/players/default_players.csv
  data/user-data/player-files/2025-04-04_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-05_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-06_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-09_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-10_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-11_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-15_Player 1_Player 2.csv
  data/user-data/player-files/2025-04-16_Player 1_Player 2.csv
  data/user-data/player-files/SNL_20250418_1744972348337.csv
  data/user-data/player-files/SNL_20250418_1744972475028.csv
  data/user-data/player-files/SNL_20250418_1744972586284.csv
  data/user-data/player-files/SNL_20250418_1744973940222.csv
  data/user-data/player-files/SNL_20250419_1745059321210.csv
  data/user-data/player-files/SNL_20250420_1745168599382.csv
  data/user-data/player-files/SNL_20250423_1745429783053.csv
  data/user-data/player-files/SNL_20250424_1745493183231.csv
  data/user-data/player-files/SNL_20250424_1745493188284.csv
  data/user-data/player-files/SNL_20250424_1745493216340.csv
  data/user-data/player-files/SNL_20250424_1745493776806.csv
  data/user-data/player-files/SNL_20250424_1745498653479.csv
  data/user-data/player-files/SNL_20250424_1745498656516.csv
  data/user-data/player-files/SNL_20250424_1745499286470.csv
  data/user-data/player-files/SNL_20250424_1745501010207.csv
  data/user-data/player-files/SNL_20250424_1745501203601.csv
  data/user-data/player-files/SNL_20250424_1745501807674.csv
  data/user-data/player-files/SNL_20250424_1745502534252.csv
  data/user-data/player-files/SNL_20250424_1745507834960.csv
  data/user-data/player-files/SNL_20250424_1745508572574.csv
  data/user-data/player-files/SNL_20250424_1745508629467.csv
  data/user-data/player-files/SNL_20250424_1745508668224.csv
Labels: bug

#104 Fix/merge issues
  data/dialogs/dialogs.json
  saves/snl_save_20250501_130446.csv
  saves/snl_save_20250501_130530.csv
  src/main/java/edu/ntnu/idi/idatt/controller/common/CharacterSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/controller/common/IntroScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/common/StarCharSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/controller/common/StarIntroScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLGameScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLRuleSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/controller/star/StarGameController.java
  src/main/java/edu/ntnu/idi/idatt/mainapp/Main.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationTarget.java
  src/main/java/edu/ntnu/idi/idatt/view/common/character/StarCharSelectionScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/common/intro/StartScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/common/intro/dialogs/InfoDialog.java
Labels: bug

#119 Feat/memoy game/create memory game
  data/dialogs/dialogs.json
  data/memorygame/memory_4x4.json
  data/memorygame/memory_4x5.json
  data/memorygame/memory_6x6.json
  data/players/default_players.csv
  saves/snl_save_20250502_123740.csv
  saves/snl_save_20250502_125706.csv
  src/main/java/edu/ntnu/idi/idatt/controller/memorygame/MemoryGameController.java
  src/main/java/edu/ntnu/idi/idatt/controller/memorygame/MemoryRuleSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/FileManager.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/handlers/DialogJsonHandler.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/handlers/MemoryJsonHandler.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/handlers/PlayerCsvHandler.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/handlers/SNLBoardJsonHandler.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/handlers/StarBoardJsonHandler.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionManager.java
  src/main/java/edu/ntnu/idi/idatt/model/common/factory/MemoryCardFactory.java
  src/main/java/edu/ntnu/idi/idatt/model/common/factory/SNLFactory.java
  src/main/java/edu/ntnu/idi/idatt/model/common/factory/StarFactory.java
  src/main/java/edu/ntnu/idi/idatt/model/common/intro/StartScreenModel.java
  src/main/java/edu/ntnu/idi/idatt/model/memorygame/MemoryBoardGame.java
  src/main/java/edu/ntnu/idi/idatt/model/memorygame/MemoryCard.java
  src/main/java/edu/ntnu/idi/idatt/model/memorygame/MemoryGameObserver.java
  src/main/java/edu/ntnu/idi/idatt/model/memorygame/MemoryGameSettings.java
  src/main/java/edu/ntnu/idi/idatt/model/memorygame/MemoryPlayer.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationTarget.java
  src/main/java/edu/ntnu/idi/idatt/view/memorygame/MemoryGameView.java
  src/main/java/edu/ntnu/idi/idatt/view/memorygame/MemoryRuleSelectionListener.java
  src/main/java/edu/ntnu/idi/idatt/view/memorygame/MemoryRuleSelectionView.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLRuleSelectionView.java
  src/main/resources/css/MemoryGameStyleSheet.css
  src/main/resources/css/RuleSelectionStyles.css
  src/main/resources/images/card_back.png
  src/main/resources/images/memory_rule_background.png
  src/main/resources/player_icons/therock.png
  src/test/java/edu/ntnu/idi/idatt/filehandling/FileManagerTest.java
  src/test/java/edu/ntnu/idi/idatt/filehandling/PlayerCsvHandlerTest.java
  src/test/java/edu/ntnu/idi/idatt/filehandling/SNLBoardJsonHandlerTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/dice/DiceTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/SNLGamePlayerTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/SNLGameTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/tile/TileTest.java
  src/test/java/edu/ntnu/idi/idatt/testutil/FixedDice.java
Labels: enhancement

#121 G UI/stargame/board
  data/custom_boards/star_game/default.json
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLGameScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/star/StarGameController.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/handlers/StarBoardJsonHandler.java
  src/main/java/edu/ntnu/idi/idatt/model/common/Tile.java
  src/main/java/edu/ntnu/idi/idatt/model/stargame/Path.java
  src/main/java/edu/ntnu/idi/idatt/model/stargame/StarBoard.java
  src/main/java/edu/ntnu/idi/idatt/model/stargame/StarGame.java
  src/main/java/edu/ntnu/idi/idatt/view/GameScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLGameScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/star/BoardCreator.java
  src/main/java/edu/ntnu/idi/idatt/view/star/StarGameView.java
  src/main/resources/images/jailTile.png
Labels: enhancement

#124 Fix/gui/snakes and ladders
  saves/snl_save_20250503_124826.csv
  saves/snl_save_20250503_125057.csv
  saves/snl_save_20250503_125322.csv
  saves/snl_save_20250503_140540.csv
  saves/snl_save_20250503_140821.csv
  saves/snl_save_20250503_141111.csv
  saves/snl_save_20250503_141151.csv
  saves/snl_save_20250503_141359.csv
  saves/snl_save_20250503_141532.csv
  saves/star_save_20250503_130233.csv
  saves/star_save_20250503_130235.csv
  src/main/java/edu/ntnu/idi/idatt/controller/paint/PaintCanvasController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLGameScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLRuleSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionManager.java
  src/main/java/edu/ntnu/idi/idatt/model/paint/PaintModel.java
  src/main/java/edu/ntnu/idi/idatt/model/paint/Stroke.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLGame.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLRuleSelectionModel.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationTarget.java
  src/main/java/edu/ntnu/idi/idatt/view/GameScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/paint/PaintCanvasView.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLGameScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLRuleSelectionView.java
  src/main/java/edu/ntnu/idi/idatt/view/star/StarGameView.java
  src/main/resources/css/SNLGameScreenStyleSheet.css
Labels: bug, enhancement

#126 Revert "Fix/gui/snakes and ladders"
  saves/snl_save_20250503_124826.csv
  saves/snl_save_20250503_125057.csv
  saves/snl_save_20250503_125322.csv
  saves/snl_save_20250503_140540.csv
  saves/snl_save_20250503_140821.csv
  saves/snl_save_20250503_141111.csv
  saves/snl_save_20250503_141151.csv
  saves/snl_save_20250503_141359.csv
  saves/snl_save_20250503_141532.csv
  saves/star_save_20250503_130233.csv
  saves/star_save_20250503_130235.csv
  src/main/java/edu/ntnu/idi/idatt/controller/paint/PaintCanvasController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLGameScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLRuleSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionManager.java
  src/main/java/edu/ntnu/idi/idatt/model/paint/PaintModel.java
  src/main/java/edu/ntnu/idi/idatt/model/paint/Stroke.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLGame.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLRuleSelectionModel.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationTarget.java
  src/main/java/edu/ntnu/idi/idatt/view/GameScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/paint/PaintCanvasView.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLGameScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLRuleSelectionView.java
  src/main/java/edu/ntnu/idi/idatt/view/star/StarGameView.java
  src/main/resources/css/SNLGameScreenStyleSheet.css
Labels: bug

#131 Fix/snlgui
  data/custom_boards/snakes_and_ladders/default.json
  data/dialogs/dialogs.json
  src/main/java/edu/ntnu/idi/idatt/controller/common/load/SNLLoadGameController.java
  src/main/java/edu/ntnu/idi/idatt/controller/paint/PaintCanvasController.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionManager.java
  src/main/java/edu/ntnu/idi/idatt/model/paint/Stroke.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLBoard.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationTarget.java
  src/main/java/edu/ntnu/idi/idatt/view/GameScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLGameScreenView.java
  src/main/resources/css/styles.css
Labels: enhancement

#135 Changes: Winnerdialogs
  src/main/java/edu/ntnu/idi/idatt/model/common/GameState.java
  src/main/java/edu/ntnu/idi/idatt/model/util/ParseHandling.java
  src/main/java/edu/ntnu/idi/idatt/view/common/game/LoadScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/common/intro/dialogs/WinnerDialogs.java
  src/main/java/edu/ntnu/idi/idatt/view/memorygame/MemoryGameView.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLGameScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/star/StarGameView.java
Labels: enhancement

#138 fix: Win Screen
  src/main/java/edu/ntnu/idi/idatt/view/common/intro/dialogs/WinnerDialogs.java
Labels: enhancement

#142 Test/test stargame model
  src/main/java/edu/ntnu/idi/idatt/model/stargame/StarBoard.java
  src/main/java/edu/ntnu/idi/idatt/model/stargame/StarGameTUI.java
  src/test/java/edu/ntnu/idi/idatt/model/stargame/StarBoardTest.java
  src/test/java/edu/ntnu/idi/idatt/model/stargame/StarGameTest.java
Labels: enhancement

#143 refactor: SNLGameTUI
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLGameTUI.java
Labels: enhancement

#144 Fix/refactor file storage
  src/main/java/edu/ntnu/idi/idatt/controller/common/CharacterSelectionController.java
  src/main/java/edu/ntnu/idi/idatt/controller/common/load/SNLLoadGameController.java
  src/main/java/edu/ntnu/idi/idatt/controller/snl/SNLGameScreenController.java
  src/main/java/edu/ntnu/idi/idatt/controller/star/StarGameController.java
  src/main/java/edu/ntnu/idi/idatt/filehandling/FileManager.java
  src/main/java/edu/ntnu/idi/idatt/model/common/BoardGame.java
  src/main/java/edu/ntnu/idi/idatt/model/common/Dice.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionManager.java
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
  src/main/java/edu/ntnu/idi/idatt/view/common/character/CharacterSelectionScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/common/character/StarCharSelectionScreen.java
  src/main/java/edu/ntnu/idi/idatt/view/snl/SNLGameScreenView.java
  src/main/java/edu/ntnu/idi/idatt/view/star/StarGameView.java
Labels: bug, enhancement

#145 Test/test memory game
  src/main/java/edu/ntnu/idi/idatt/model/memorygame/MemoryBoardGame.java
  src/test/java/edu/ntnu/idi/idatt/model/common/memory/MemoryBoardGameTest.java
  src/test/java/edu/ntnu/idi/idatt/model/memorygame/MemoryBoardGameTest.java
  src/test/java/edu/ntnu/idi/idatt/model/memorygame/MemoryCardTest.java
  src/test/java/edu/ntnu/idi/idatt/model/memorygame/MemoryGameSettingsTest.java
  src/test/java/edu/ntnu/idi/idatt/model/memorygame/MemoryPlayerTest.java
Labels: documentation, enhancement

#146 test: Paint Model
  src/test/java/edu/ntnu/idi/idatt/model/paint/PaintModelTest.java
  src/test/java/edu/ntnu/idi/idatt/model/paint/StrokeTest.java
Labels: documentation, enhancement

#147 Test/test general model classes
  src/main/java/edu/ntnu/idi/idatt/model/common/BoardGame.java
  src/main/java/edu/ntnu/idi/idatt/model/common/BoardGameFactory.java
  src/main/java/edu/ntnu/idi/idatt/model/common/Dice.java
  src/main/java/edu/ntnu/idi/idatt/model/common/Die.java
  src/main/java/edu/ntnu/idi/idatt/model/common/GameState.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionCSVExporter.java
  src/main/java/edu/ntnu/idi/idatt/model/common/character_selection/CharacterSelectionData.java
  src/main/java/edu/ntnu/idi/idatt/model/common/factory/SNLFactory.java
  src/main/java/edu/ntnu/idi/idatt/model/common/factory/StarFactory.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLBoard.java
  src/main/java/edu/ntnu/idi/idatt/model/snl/SNLRuleSelectionModel.java
  src/test/java/edu/ntnu/idi/idatt/model/common/AbstractBoardTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/BoardGameTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/DiceTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/DieTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/PlayerTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/TileTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/charachter_selection/CharacterSelectionManagerTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/dice/DiceTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/factory/SNLFactoryTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/factory/StarFactoryTest.java
  src/test/java/edu/ntnu/idi/idatt/model/common/intro/StartScreenModelTest.java
  src/test/java/edu/ntnu/idi/idatt/model/memorygame/MemoryBoardGameTest.java
  src/test/java/edu/ntnu/idi/idatt/model/memorygame/MemoryGameSettingsTest.java
  src/test/java/edu/ntnu/idi/idatt/model/paint/StrokeTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/LadderTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/SNLBoardTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/SNLGameTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/SNLRuleSelectionModelTest.java
  src/test/java/edu/ntnu/idi/idatt/model/snl/SnakeTest.java
  src/test/java/edu/ntnu/idi/idatt/model/stargame/StarBoardTest.java
  src/test/java/edu/ntnu/idi/idatt/model/stargame/StarGameTest.java
Labels: documentation, enhancement

#149 fix: Back Button
  src/main/java/edu/ntnu/idi/idatt/navigation/NavigationManager.java
Labels: bug

#154 fix: Fullscreen
  src/main/java/edu/ntnu/idi/idatt/mainapp/Main.java
Labels: enhancement
